/*
 * @Author: zerotower69 zerotower@163.com
 * @Date: 2022-12-16 22:02:46
 * @LastEditors: zerotower69 zerotower@163.com
 * @LastEditTime: 2022-12-16 22:03:20
 * @FilePath: /vue3-blog/components.d.ts
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default'];
  }
}

export {}
